In [7]:
import numpy as np
from scipy.stats import unitary_group

I = np.array([[1, 0], [0, 1]])

X = np.array([[0, 1], [1, 0]])
             
Y = np.array([[0, -1j], [1j, 0]])
             
Z = np.array([[1, 0], [0, -1]])

H = (1/np.sqrt(2)) * np.array([[1, 1], [1, -1]])

S = np.array([[1, 0], [0, 1j]])

T = np.array([[1, 0], [0, np.exp(1j*np.pi/4)]])

CNOT = np.array([[1,0,0,0], [0,1,0,0], [0,0,0,1], [0,0,1,0]])

In [70]:
def n_qubit_circuit(n, input_state, gates):
    output_state = np.array([0 for i in range(2**n)], dtype = np.complex128) # FIXED
    
    for j in input_state.keys():
        curr_bin = int(''.join(list(map(str, j))), 2) #FIXED
        output_state[curr_bin] = input_state[j]  #FIXED
    
    for i in range(len(gates)):
        flag = list(n for n in range(2**n))
        U = gates[i][0] # FIXED
        target = gates[i][1]
        while len(flag) > 0:
            mask = 1 << (n - target - 1)
            not_mask = (2**n - 1) ^ mask
            state1 = not_mask & flag[0]
            state2 = mask | flag[0]
            flag.remove(state1)
            flag.remove(state2)
            output_state[state1], output_state[state2] = output_state[state1] * U[0, 0] + output_state[state2] * U[0, 1], output_state[state1] * U[1,0] + output_state[state2] * U[1, 1]
            
    return output_state 

In [71]:
n = 3
input_state = {(0,0,0) : 0.5, (0,1,0) : 0.5, (1,0,1) : 0.5, (1,1,0) : 0.5}

gates = [[U1, 0], [U2, 1], [U3, 0]]
print(n_qubit_circuit(n, input_state, gates))

[-0.09094983-0.47344717j -0.0691966 +0.0561723j  -0.01792159-0.3210979j
  0.41489255-0.14304753j  0.29055226+0.31246478j -0.04009308-0.01875067j
 -0.34353134+0.3377606j   0.15381223+0.15440478j]


In [63]:
# генерация случайных унитарных матриц для проверки работы кода
U1 = unitary_group.rvs(2)
U2 = unitary_group.rvs(2)
U3 = unitary_group.rvs(2)

In [64]:
U1

array([[-0.133756  -0.31497357j,  0.65875781-0.6700292j ],
       [-0.83399631-0.43284077j, -0.02953899+0.34092003j]])

In [65]:
U2

array([[ 0.19696912-0.02851888j, -0.66338078+0.72132918j],
       [-0.95925998-0.20052465j, -0.17677445+0.09143826j]])

In [66]:
U3

array([[-0.96621977-0.22010785j, -0.13006907-0.03246434j],
       [ 0.03928988-0.12817254j, -0.30990139+0.94127001j]])